// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lists/base/property_list.proto

package base

import (
	fmt "fmt"
	base "github.com/AssetMantle/schema/go/properties/base"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type PropertyList struct {
	Properties []*base.AnyProperty `protobuf:"bytes,1,rep,name=properties,proto3" json:"properties,omitempty"`
}

func (m *PropertyList) Reset()         { *m = PropertyList{} }
func (m *PropertyList) String() string { return proto.CompactTextString(m) }
func (*PropertyList) ProtoMessage()    {}
func (*PropertyList) Descriptor() ([]byte, []int) {
	return fileDescriptor_62f5ec8192eb15d6, []int{0}
}
func (m *PropertyList) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PropertyList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PropertyList.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PropertyList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PropertyList.Merge(m, src)
}
func (m *PropertyList) XXX_Size() int {
	return m.Size()
}
func (m *PropertyList) XXX_DiscardUnknown() {
	xxx_messageInfo_PropertyList.DiscardUnknown(m)
}

var xxx_messageInfo_PropertyList proto.InternalMessageInfo

func init() {
	proto.RegisterType((*PropertyList)(nil), "assetmantle.schema.lists.base.PropertyList")
}

func init() { proto.RegisterFile("lists/base/property_list.proto", fileDescriptor_62f5ec8192eb15d6) }

var fileDescriptor_62f5ec8192eb15d6 = []byte{
	// 307 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xcb, 0xc9, 0x2c, 0x2e,
	0x29, 0xd6, 0x4f, 0x4a, 0x2c, 0x4e, 0xd5, 0x2f, 0x28, 0xca, 0x2f, 0x48, 0x2d, 0x2a, 0xa9, 0x8c,
	0x07, 0x89, 0xe9, 0x15, 0x14, 0xe5, 0x97, 0xe4, 0x0b, 0xc9, 0x26, 0x16, 0x17, 0xa7, 0x96, 0xe4,
	0x26, 0xe6, 0x95, 0xe4, 0xa4, 0xea, 0x15, 0x27, 0x67, 0xa4, 0xe6, 0x26, 0xea, 0x81, 0xb5, 0xe8,
	0x81, 0xb4, 0x48, 0x29, 0x41, 0xf5, 0x64, 0xa6, 0x42, 0xcd, 0x48, 0xcc, 0xab, 0x8c, 0x87, 0x99,
	0x03, 0x31, 0x42, 0x4a, 0x24, 0x3d, 0x3f, 0x3d, 0x1f, 0xcc, 0xd4, 0x07, 0xb1, 0x20, 0xa2, 0x4a,
	0xa9, 0x5c, 0x3c, 0x01, 0x50, 0x75, 0x3e, 0x99, 0xc5, 0x25, 0x42, 0xfe, 0x5c, 0x5c, 0x08, 0xb3,
	0x24, 0x18, 0x15, 0x98, 0x35, 0xb8, 0x8d, 0xf4, 0xf5, 0xb0, 0xd8, 0x8e, 0x50, 0x05, 0x76, 0x82,
	0x9e, 0x63, 0x5e, 0x25, 0xcc, 0xa0, 0x20, 0x24, 0x23, 0xac, 0x58, 0x3a, 0x16, 0xc8, 0x33, 0x38,
	0x4d, 0x66, 0x3a, 0xf1, 0x48, 0x8e, 0xf1, 0xc2, 0x23, 0x39, 0xc6, 0x07, 0x8f, 0xe4, 0x18, 0x27,
	0x3c, 0x96, 0x63, 0xb8, 0xf0, 0x58, 0x8e, 0xe1, 0xc6, 0x63, 0x39, 0x06, 0x2e, 0xc5, 0xe4, 0xfc,
	0x5c, 0x3d, 0xbc, 0xde, 0x73, 0x12, 0x44, 0x76, 0x62, 0x00, 0xc8, 0xdd, 0x01, 0x8c, 0x51, 0xda,
	0xe9, 0x99, 0x25, 0x19, 0xa5, 0x49, 0x7a, 0xc9, 0xf9, 0xb9, 0xfa, 0x8e, 0x20, 0xed, 0xbe, 0x60,
	0xed, 0xfa, 0x10, 0xed, 0xfa, 0xe9, 0xf9, 0xfa, 0x88, 0x30, 0x5d, 0xc4, 0xc4, 0xe2, 0x18, 0xec,
	0xe3, 0xb4, 0x8a, 0x49, 0xd6, 0x11, 0xc9, 0xa2, 0x60, 0x88, 0x45, 0x3e, 0x60, 0x8b, 0x9c, 0x12,
	0x8b, 0x53, 0x4f, 0xa1, 0xc8, 0xc7, 0x40, 0xe4, 0x63, 0xc0, 0xf2, 0x31, 0x20, 0xf9, 0x47, 0x4c,
	0x9a, 0x78, 0xe5, 0x63, 0xdc, 0x03, 0x9c, 0x7c, 0x53, 0x4b, 0x12, 0x53, 0x12, 0x4b, 0x12, 0x5f,
	0x31, 0x29, 0x20, 0xa9, 0xb5, 0xb2, 0x82, 0x28, 0xb6, 0xb2, 0x02, 0xab, 0xb6, 0xb2, 0x02, 0x29,
	0x4f, 0x62, 0x03, 0xc7, 0x81, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x76, 0xaa, 0x93, 0x60, 0xfe,
	0x01, 0x00, 0x00,
}

func (m *PropertyList) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PropertyList) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PropertyList) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Properties) > 0 {
		for iNdEx := len(m.Properties) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Properties[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPropertyList(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintPropertyList(dAtA []byte, offset int, v uint64) int {
	offset -= sovPropertyList(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *PropertyList) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Properties) > 0 {
		for _, e := range m.Properties {
			l = e.Size()
			n += 1 + l + sovPropertyList(uint64(l))
		}
	}
	return n
}

func sovPropertyList(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPropertyList(x uint64) (n int) {
	return sovPropertyList(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *PropertyList) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPropertyList
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PropertyList: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PropertyList: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Properties", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPropertyList
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPropertyList
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPropertyList
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Properties = append(m.Properties, &base.AnyProperty{})
			if err := m.Properties[len(m.Properties)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPropertyList(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPropertyList
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPropertyList(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPropertyList
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPropertyList
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPropertyList
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPropertyList
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPropertyList
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPropertyList
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPropertyList        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPropertyList          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPropertyList = fmt.Errorf("proto: unexpected end of group")
)
