// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: AssetMantle/schema/lists/base/parameter_list.proto

package base

import (
	fmt "fmt"
	base "github.com/AssetMantle/schema/parameters/base"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ParameterList struct {
	Parameters []*base.Parameter `protobuf:"bytes,1,rep,name=parameters,proto3" json:"parameters,omitempty"`
}

func (m *ParameterList) Reset()         { *m = ParameterList{} }
func (m *ParameterList) String() string { return proto.CompactTextString(m) }
func (*ParameterList) ProtoMessage()    {}
func (*ParameterList) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f40189101f82f74, []int{0}
}
func (m *ParameterList) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ParameterList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ParameterList.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ParameterList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParameterList.Merge(m, src)
}
func (m *ParameterList) XXX_Size() int {
	return m.Size()
}
func (m *ParameterList) XXX_DiscardUnknown() {
	xxx_messageInfo_ParameterList.DiscardUnknown(m)
}

var xxx_messageInfo_ParameterList proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ParameterList)(nil), "AssetMantle.schema.lists.base.ParameterList")
}

func init() {
	proto.RegisterFile("AssetMantle/schema/lists/base/parameter_list.proto", fileDescriptor_7f40189101f82f74)
}

var fileDescriptor_7f40189101f82f74 = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x72, 0x2c, 0x2e, 0x4e,
	0x2d, 0xf1, 0x4d, 0xcc, 0x2b, 0xc9, 0x49, 0xd5, 0x2f, 0x4e, 0xce, 0x48, 0xcd, 0x4d, 0xd4, 0xcf,
	0xc9, 0x2c, 0x2e, 0x29, 0xd6, 0x4f, 0x4a, 0x2c, 0x4e, 0xd5, 0x2f, 0x48, 0x2c, 0x4a, 0xcc, 0x4d,
	0x2d, 0x49, 0x2d, 0x8a, 0x07, 0x09, 0xea, 0x15, 0x14, 0xe5, 0x97, 0xe4, 0x0b, 0xc9, 0x22, 0xe9,
	0xd1, 0x83, 0xe8, 0xd1, 0x03, 0xeb, 0xd1, 0x03, 0xe9, 0x91, 0x12, 0x49, 0xcf, 0x4f, 0xcf, 0x07,
	0xab, 0xd4, 0x07, 0xb1, 0x20, 0x9a, 0xa4, 0xb0, 0x59, 0x04, 0x37, 0x1d, 0xdd, 0x36, 0x88, 0x1e,
	0xa5, 0x14, 0x2e, 0xde, 0x00, 0x98, 0x90, 0x4f, 0x66, 0x71, 0x89, 0x90, 0x2f, 0x17, 0x17, 0x42,
	0x8f, 0x04, 0xa3, 0x02, 0xb3, 0x06, 0xb7, 0x91, 0xae, 0x1e, 0x16, 0xe7, 0x20, 0x54, 0x81, 0xdd,
	0xa4, 0x07, 0x37, 0x26, 0x08, 0xc9, 0x00, 0x2b, 0x96, 0x8e, 0x05, 0xf2, 0x0c, 0x4e, 0x13, 0x99,
	0x4e, 0x3c, 0x92, 0x63, 0xbc, 0xf0, 0x48, 0x8e, 0xf1, 0xc1, 0x23, 0x39, 0xc6, 0x09, 0x8f, 0xe5,
	0x18, 0x2e, 0x3c, 0x96, 0x63, 0xb8, 0xf1, 0x58, 0x8e, 0x81, 0x4b, 0x31, 0x39, 0x3f, 0x57, 0x0f,
	0xaf, 0x6f, 0x9d, 0x84, 0x50, 0x5c, 0x18, 0x00, 0x72, 0x77, 0x00, 0x63, 0x94, 0x46, 0x7a, 0x66,
	0x49, 0x46, 0x69, 0x92, 0x5e, 0x72, 0x7e, 0xae, 0x3e, 0xde, 0x10, 0x5e, 0xc4, 0xc4, 0xe2, 0x18,
	0xec, 0xe3, 0xb4, 0x8a, 0x09, 0x25, 0x50, 0x83, 0x21, 0xd6, 0xf8, 0x80, 0xad, 0x71, 0x4a, 0x2c,
	0x4e, 0x3d, 0x85, 0x22, 0x1f, 0x03, 0x91, 0x8f, 0x01, 0xcb, 0xc7, 0x80, 0xe4, 0x1f, 0x31, 0x69,
	0xe2, 0x95, 0x8f, 0x71, 0x0f, 0x70, 0xf2, 0x4d, 0x2d, 0x49, 0x4c, 0x49, 0x2c, 0x49, 0x7c, 0xc5,
	0xa4, 0x80, 0xa4, 0xd6, 0xca, 0x0a, 0xa2, 0xd8, 0xca, 0x0a, 0xac, 0xda, 0xca, 0x0a, 0xa4, 0x3c,
	0x89, 0x0d, 0x1c, 0x01, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xcb, 0xcc, 0x4e, 0x0d, 0x1f,
	0x02, 0x00, 0x00,
}

func (m *ParameterList) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ParameterList) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ParameterList) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Parameters) > 0 {
		for iNdEx := len(m.Parameters) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Parameters[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParameterList(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintParameterList(dAtA []byte, offset int, v uint64) int {
	offset -= sovParameterList(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ParameterList) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Parameters) > 0 {
		for _, e := range m.Parameters {
			l = e.Size()
			n += 1 + l + sovParameterList(uint64(l))
		}
	}
	return n
}

func sovParameterList(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParameterList(x uint64) (n int) {
	return sovParameterList(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ParameterList) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParameterList
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ParameterList: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ParameterList: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Parameters", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParameterList
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParameterList
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParameterList
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Parameters = append(m.Parameters, &base.Parameter{})
			if err := m.Parameters[len(m.Parameters)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParameterList(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParameterList
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParameterList(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParameterList
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParameterList
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParameterList
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParameterList
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParameterList
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParameterList
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParameterList        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParameterList          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParameterList = fmt.Errorf("proto: unexpected end of group")
)
