// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: data/base/any_listable_data.proto

package base

import (
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/gogo/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type AnyListableData struct {
	// Types that are valid to be assigned to Impl:
	//	*AnyListableData_AccAddressData
	//	*AnyListableData_BooleanData
	//	*AnyListableData_DecData
	//	*AnyListableData_HeightData
	//	*AnyListableData_IDData
	//	*AnyListableData_NumberData
	//	*AnyListableData_StringData
	Impl isAnyListableData_Impl `protobuf_oneof:"impl"`
}

func (m *AnyListableData) Reset()         { *m = AnyListableData{} }
func (m *AnyListableData) String() string { return proto.CompactTextString(m) }
func (*AnyListableData) ProtoMessage()    {}
func (*AnyListableData) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3606df89b57fc4, []int{0}
}
func (m *AnyListableData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AnyListableData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AnyListableData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AnyListableData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnyListableData.Merge(m, src)
}
func (m *AnyListableData) XXX_Size() int {
	return m.Size()
}
func (m *AnyListableData) XXX_DiscardUnknown() {
	xxx_messageInfo_AnyListableData.DiscardUnknown(m)
}

var xxx_messageInfo_AnyListableData proto.InternalMessageInfo

type isAnyListableData_Impl interface {
	isAnyListableData_Impl()
	MarshalTo([]byte) (int, error)
	Size() int
}

type AnyListableData_AccAddressData struct {
	AccAddressData *AccAddressData `protobuf:"bytes,1,opt,name=acc_address_data,json=accAddressData,proto3,oneof" json:"acc_address_data,omitempty"`
}
type AnyListableData_BooleanData struct {
	BooleanData *BooleanData `protobuf:"bytes,2,opt,name=boolean_data,json=booleanData,proto3,oneof" json:"boolean_data,omitempty"`
}
type AnyListableData_DecData struct {
	DecData *DecData `protobuf:"bytes,3,opt,name=dec_data,json=decData,proto3,oneof" json:"dec_data,omitempty"`
}
type AnyListableData_HeightData struct {
	HeightData *HeightData `protobuf:"bytes,4,opt,name=height_data,json=heightData,proto3,oneof" json:"height_data,omitempty"`
}
type AnyListableData_IDData struct {
	IDData *IDData `protobuf:"bytes,5,opt,name=i_d_data,json=iDData,proto3,oneof" json:"i_d_data,omitempty"`
}
type AnyListableData_NumberData struct {
	NumberData *NumberData `protobuf:"bytes,7,opt,name=number_data,json=numberData,proto3,oneof" json:"number_data,omitempty"`
}
type AnyListableData_StringData struct {
	StringData *StringData `protobuf:"bytes,8,opt,name=string_data,json=stringData,proto3,oneof" json:"string_data,omitempty"`
}

func (*AnyListableData_AccAddressData) isAnyListableData_Impl() {}
func (*AnyListableData_BooleanData) isAnyListableData_Impl()    {}
func (*AnyListableData_DecData) isAnyListableData_Impl()        {}
func (*AnyListableData_HeightData) isAnyListableData_Impl()     {}
func (*AnyListableData_IDData) isAnyListableData_Impl()         {}
func (*AnyListableData_NumberData) isAnyListableData_Impl()     {}
func (*AnyListableData_StringData) isAnyListableData_Impl()     {}

func (m *AnyListableData) GetImpl() isAnyListableData_Impl {
	if m != nil {
		return m.Impl
	}
	return nil
}

func (m *AnyListableData) GetAccAddressData() *AccAddressData {
	if x, ok := m.GetImpl().(*AnyListableData_AccAddressData); ok {
		return x.AccAddressData
	}
	return nil
}

func (m *AnyListableData) GetBooleanData() *BooleanData {
	if x, ok := m.GetImpl().(*AnyListableData_BooleanData); ok {
		return x.BooleanData
	}
	return nil
}

func (m *AnyListableData) GetDecData() *DecData {
	if x, ok := m.GetImpl().(*AnyListableData_DecData); ok {
		return x.DecData
	}
	return nil
}

func (m *AnyListableData) GetHeightData() *HeightData {
	if x, ok := m.GetImpl().(*AnyListableData_HeightData); ok {
		return x.HeightData
	}
	return nil
}

func (m *AnyListableData) GetIDData() *IDData {
	if x, ok := m.GetImpl().(*AnyListableData_IDData); ok {
		return x.IDData
	}
	return nil
}

func (m *AnyListableData) GetNumberData() *NumberData {
	if x, ok := m.GetImpl().(*AnyListableData_NumberData); ok {
		return x.NumberData
	}
	return nil
}

func (m *AnyListableData) GetStringData() *StringData {
	if x, ok := m.GetImpl().(*AnyListableData_StringData); ok {
		return x.StringData
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*AnyListableData) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*AnyListableData_AccAddressData)(nil),
		(*AnyListableData_BooleanData)(nil),
		(*AnyListableData_DecData)(nil),
		(*AnyListableData_HeightData)(nil),
		(*AnyListableData_IDData)(nil),
		(*AnyListableData_NumberData)(nil),
		(*AnyListableData_StringData)(nil),
	}
}

func init() {
	proto.RegisterType((*AnyListableData)(nil), "assetmantle.schema.data.base.AnyListableData")
}

func init() { proto.RegisterFile("data/base/any_listable_data.proto", fileDescriptor_2b3606df89b57fc4) }

var fileDescriptor_2b3606df89b57fc4 = []byte{
	// 488 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0x41, 0x6b, 0xd4, 0x40,
	0x14, 0xc7, 0x93, 0x18, 0xb7, 0xcb, 0xac, 0xa8, 0x84, 0x82, 0xa1, 0x2e, 0xe9, 0x2a, 0x0a, 0xab,
	0x48, 0x02, 0x7a, 0xcb, 0xc9, 0x0c, 0x01, 0x2b, 0xda, 0xb2, 0xb8, 0x17, 0x91, 0x85, 0x65, 0x32,
	0x19, 0x92, 0x81, 0x24, 0x53, 0x76, 0xa6, 0x87, 0x7e, 0x03, 0x8f, 0xfd, 0x08, 0xe2, 0xd1, 0x0f,
	0xe0, 0x67, 0x10, 0x4f, 0x3d, 0x7a, 0x94, 0xdd, 0x9b, 0x9f, 0x42, 0x66, 0x26, 0xbb, 0x99, 0x16,
	0x1a, 0x7a, 0x9b, 0x37, 0xff, 0xf7, 0xff, 0xbd, 0x97, 0x37, 0x2f, 0xe0, 0x49, 0x8e, 0x04, 0x8a,
	0x32, 0xc4, 0x49, 0x84, 0x9a, 0xf3, 0x65, 0x45, 0xb9, 0x40, 0x59, 0x45, 0x96, 0xf2, 0x3a, 0x3c,
	0x5d, 0x31, 0xc1, 0xbc, 0x31, 0xe2, 0x9c, 0x88, 0x1a, 0x35, 0xa2, 0x22, 0x21, 0xc7, 0x25, 0xa9,
	0x51, 0xa8, 0x64, 0xe9, 0x3a, 0x98, 0x18, 0x00, 0x8c, 0x97, 0x28, 0xcf, 0x57, 0x84, 0x73, 0xc3,
	0x7f, 0x30, 0xee, 0x32, 0x32, 0xc6, 0x2a, 0x82, 0x1a, 0x53, 0xf5, 0x3b, 0x35, 0x27, 0xd8, 0x54,
	0x1e, 0x77, 0x4a, 0x49, 0x68, 0x51, 0x0a, 0x53, 0x7c, 0xd4, 0x89, 0x34, 0xbf, 0xc1, 0xd5, 0x9c,
	0xd5, 0x19, 0x59, 0xdd, 0x20, 0x72, 0xb1, 0xa2, 0x4d, 0x61, 0x8a, 0xfb, 0x05, 0x2b, 0x98, 0x3a,
	0x46, 0xf2, 0xa4, 0x6f, 0x9f, 0xfe, 0x74, 0xc1, 0x83, 0xa4, 0x39, 0xff, 0xd8, 0x0e, 0x26, 0x45,
	0x02, 0x79, 0x9f, 0xc1, 0xc3, 0xeb, 0xdf, 0xea, 0xdb, 0x13, 0x7b, 0x3a, 0x7a, 0xfd, 0x2a, 0xec,
	0x1b, 0x56, 0x98, 0x60, 0x9c, 0x68, 0x93, 0xe4, 0x1c, 0x59, 0x9f, 0xee, 0xa3, 0x2b, 0x37, 0xde,
	0x09, 0xb8, 0x67, 0xce, 0xc8, 0x77, 0x14, 0xf5, 0x45, 0x3f, 0x15, 0x6a, 0x47, 0x8b, 0x1c, 0x65,
	0x5d, 0xe8, 0x41, 0x30, 0xdc, 0x4e, 0xd5, 0xbf, 0xa3, 0x58, 0xcf, 0xfb, 0x59, 0x29, 0xc1, 0x2d,
	0x67, 0x2f, 0xd7, 0x47, 0xef, 0x03, 0x18, 0x19, 0xf3, 0xf7, 0x5d, 0x85, 0x99, 0xf6, 0x63, 0x8e,
	0x94, 0xa1, 0x25, 0x81, 0x72, 0x17, 0x79, 0x6f, 0xc1, 0x90, 0x2e, 0xf5, 0x83, 0xf9, 0x77, 0x15,
	0xe9, 0x59, 0x3f, 0xe9, 0x7d, 0xda, 0x52, 0x06, 0x34, 0xdd, 0xb6, 0x63, 0x3c, 0xac, 0xbf, 0x77,
	0x9b, 0x76, 0x4e, 0x94, 0x61, 0xdb, 0x4e, 0xb3, 0x8b, 0x24, 0xcc, 0x58, 0x04, 0x7f, 0x78, 0x1b,
	0xd8, 0x5c, 0x19, 0xb6, 0x30, 0xbe, 0x8b, 0x62, 0xf7, 0xeb, 0xb7, 0x43, 0x0b, 0x0e, 0x80, 0x4b,
	0xeb, 0xd3, 0x0a, 0x5e, 0x38, 0xbf, 0xd6, 0x81, 0x7d, 0xb9, 0x0e, 0xec, 0xbf, 0xeb, 0xc0, 0xbe,
	0xd8, 0x04, 0xd6, 0xe5, 0x26, 0xb0, 0xfe, 0x6c, 0x02, 0x0b, 0x4c, 0x30, 0xab, 0x7b, 0x6b, 0xc0,
	0xfd, 0x6b, 0x2b, 0x37, 0x93, 0xbb, 0x38, 0xb3, 0xbf, 0xbc, 0x2c, 0xa8, 0x28, 0xcf, 0xb2, 0x10,
	0xb3, 0x3a, 0x4a, 0x24, 0xe0, 0x58, 0x01, 0x22, 0x0d, 0x88, 0x0a, 0x16, 0xed, 0x36, 0xfc, 0xbb,
	0xe3, 0x26, 0xf3, 0x14, 0xfe, 0x70, 0xc6, 0x89, 0x51, 0x69, 0xae, 0x2b, 0x49, 0x66, 0x08, 0x11,
	0x27, 0xbf, 0xaf, 0xc8, 0x0b, 0x2d, 0x2f, 0xa4, 0xbc, 0x90, 0xf2, 0xda, 0x99, 0xf6, 0xc9, 0x8b,
	0x77, 0x33, 0x78, 0x4c, 0x04, 0x92, 0x45, 0xff, 0x39, 0x87, 0x46, 0x6a, 0x1c, 0xeb, 0xdc, 0x38,
	0x56, 0xa3, 0x89, 0x65, 0x76, 0x36, 0x50, 0xbf, 0xd4, 0x9b, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x59, 0x48, 0x47, 0x9a, 0x75, 0x04, 0x00, 0x00,
}

func (m *AnyListableData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AnyListableData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AnyListableData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Impl != nil {
		{
			size := m.Impl.Size()
			i -= size
			if _, err := m.Impl.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	return len(dAtA) - i, nil
}

func (m *AnyListableData_AccAddressData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AnyListableData_AccAddressData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.AccAddressData != nil {
		{
			size, err := m.AccAddressData.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAnyListableData(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}
func (m *AnyListableData_BooleanData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AnyListableData_BooleanData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.BooleanData != nil {
		{
			size, err := m.BooleanData.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAnyListableData(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}
func (m *AnyListableData_DecData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AnyListableData_DecData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.DecData != nil {
		{
			size, err := m.DecData.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAnyListableData(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	return len(dAtA) - i, nil
}
func (m *AnyListableData_HeightData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AnyListableData_HeightData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.HeightData != nil {
		{
			size, err := m.HeightData.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAnyListableData(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	return len(dAtA) - i, nil
}
func (m *AnyListableData_IDData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AnyListableData_IDData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.IDData != nil {
		{
			size, err := m.IDData.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAnyListableData(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	return len(dAtA) - i, nil
}
func (m *AnyListableData_NumberData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AnyListableData_NumberData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.NumberData != nil {
		{
			size, err := m.NumberData.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAnyListableData(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x3a
	}
	return len(dAtA) - i, nil
}
func (m *AnyListableData_StringData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AnyListableData_StringData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.StringData != nil {
		{
			size, err := m.StringData.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAnyListableData(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x42
	}
	return len(dAtA) - i, nil
}
func encodeVarintAnyListableData(dAtA []byte, offset int, v uint64) int {
	offset -= sovAnyListableData(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AnyListableData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Impl != nil {
		n += m.Impl.Size()
	}
	return n
}

func (m *AnyListableData_AccAddressData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AccAddressData != nil {
		l = m.AccAddressData.Size()
		n += 1 + l + sovAnyListableData(uint64(l))
	}
	return n
}
func (m *AnyListableData_BooleanData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BooleanData != nil {
		l = m.BooleanData.Size()
		n += 1 + l + sovAnyListableData(uint64(l))
	}
	return n
}
func (m *AnyListableData_DecData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DecData != nil {
		l = m.DecData.Size()
		n += 1 + l + sovAnyListableData(uint64(l))
	}
	return n
}
func (m *AnyListableData_HeightData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.HeightData != nil {
		l = m.HeightData.Size()
		n += 1 + l + sovAnyListableData(uint64(l))
	}
	return n
}
func (m *AnyListableData_IDData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.IDData != nil {
		l = m.IDData.Size()
		n += 1 + l + sovAnyListableData(uint64(l))
	}
	return n
}
func (m *AnyListableData_NumberData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.NumberData != nil {
		l = m.NumberData.Size()
		n += 1 + l + sovAnyListableData(uint64(l))
	}
	return n
}
func (m *AnyListableData_StringData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.StringData != nil {
		l = m.StringData.Size()
		n += 1 + l + sovAnyListableData(uint64(l))
	}
	return n
}

func sovAnyListableData(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAnyListableData(x uint64) (n int) {
	return sovAnyListableData(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *AnyListableData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAnyListableData
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AnyListableData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AnyListableData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccAddressData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAnyListableData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAnyListableData
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAnyListableData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &AccAddressData{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Impl = &AnyListableData_AccAddressData{v}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BooleanData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAnyListableData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAnyListableData
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAnyListableData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &BooleanData{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Impl = &AnyListableData_BooleanData{v}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DecData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAnyListableData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAnyListableData
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAnyListableData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &DecData{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Impl = &AnyListableData_DecData{v}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HeightData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAnyListableData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAnyListableData
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAnyListableData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &HeightData{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Impl = &AnyListableData_HeightData{v}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IDData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAnyListableData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAnyListableData
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAnyListableData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &IDData{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Impl = &AnyListableData_IDData{v}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NumberData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAnyListableData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAnyListableData
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAnyListableData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &NumberData{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Impl = &AnyListableData_NumberData{v}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StringData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAnyListableData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAnyListableData
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAnyListableData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &StringData{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Impl = &AnyListableData_StringData{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAnyListableData(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAnyListableData
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAnyListableData(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAnyListableData
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAnyListableData
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAnyListableData
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAnyListableData
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAnyListableData
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAnyListableData
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAnyListableData        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAnyListableData          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAnyListableData = fmt.Errorf("proto: unexpected end of group")
)
