// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: data/base/id_data.proto

package base

import (
	fmt "fmt"
	base "github.com/AssetMantle/schema/go/ids/base"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type IDData struct {
	Value *base.AnyID `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *IDData) Reset()         { *m = IDData{} }
func (m *IDData) String() string { return proto.CompactTextString(m) }
func (*IDData) ProtoMessage()    {}
func (*IDData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8dc4f319ae578334, []int{0}
}
func (m *IDData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *IDData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_IDData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *IDData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IDData.Merge(m, src)
}
func (m *IDData) XXX_Size() int {
	return m.Size()
}
func (m *IDData) XXX_DiscardUnknown() {
	xxx_messageInfo_IDData.DiscardUnknown(m)
}

var xxx_messageInfo_IDData proto.InternalMessageInfo

func init() {
	proto.RegisterType((*IDData)(nil), "data.base.IDData")
}

func init() { proto.RegisterFile("data/base/id_data.proto", fileDescriptor_8dc4f319ae578334) }

var fileDescriptor_8dc4f319ae578334 = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4f, 0x49, 0x2c, 0x49,
	0xd4, 0x4f, 0x4a, 0x2c, 0x4e, 0xd5, 0xcf, 0x4c, 0x89, 0x07, 0x71, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b,
	0xf2, 0x85, 0x38, 0xc1, 0x6c, 0x90, 0x84, 0x94, 0x68, 0x66, 0x4a, 0x31, 0x44, 0x49, 0x62, 0x5e,
	0x65, 0x7c, 0x66, 0x0a, 0x44, 0x85, 0x94, 0x48, 0x7a, 0x7e, 0x7a, 0x3e, 0x98, 0xa9, 0x0f, 0x62,
	0x41, 0x44, 0x95, 0x4c, 0xb9, 0xd8, 0x3c, 0x5d, 0x5c, 0x12, 0x4b, 0x12, 0x85, 0x54, 0xb9, 0x58,
	0xcb, 0x12, 0x73, 0x4a, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0xb8, 0x8d, 0xf8, 0xf5, 0x32, 0x53,
	0x8a, 0xc1, 0x06, 0xea, 0x39, 0xe6, 0x55, 0x7a, 0xba, 0x04, 0x41, 0x64, 0xad, 0x58, 0x3a, 0x16,
	0xc8, 0x33, 0x38, 0x2d, 0x65, 0x3c, 0xf1, 0x48, 0x8e, 0xf1, 0xc2, 0x23, 0x39, 0xc6, 0x07, 0x8f,
	0xe4, 0x18, 0x27, 0x3c, 0x96, 0x63, 0xb8, 0xf0, 0x58, 0x8e, 0xe1, 0xc6, 0x63, 0x39, 0x06, 0x2e,
	0xde, 0xe4, 0xfc, 0x5c, 0x3d, 0xb8, 0x6b, 0x9c, 0xb8, 0x3d, 0x53, 0x40, 0xc6, 0x07, 0x80, 0x6c,
	0x0b, 0x60, 0x8c, 0xd2, 0x4a, 0xcf, 0x2c, 0xc9, 0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x77,
	0x2c, 0x2e, 0x4e, 0x2d, 0xf1, 0x4d, 0xcc, 0x2b, 0xc9, 0x49, 0xd5, 0x2f, 0x4e, 0xce, 0x48, 0xcd,
	0x4d, 0xd4, 0x4f, 0xcf, 0xd7, 0x87, 0xfb, 0x70, 0x11, 0x13, 0xb3, 0x8b, 0x53, 0xc4, 0x2a, 0x26,
	0x4e, 0x90, 0x7e, 0x3d, 0xa7, 0xc4, 0xe2, 0xd4, 0x53, 0x10, 0x76, 0x0c, 0x88, 0xfd, 0x88, 0x49,
	0x14, 0xce, 0x8e, 0x71, 0x0f, 0x70, 0xf2, 0x4d, 0x2d, 0x49, 0x04, 0x69, 0x7d, 0xc5, 0xc4, 0x05,
	0x12, 0xb7, 0xb2, 0x02, 0x49, 0x24, 0xb1, 0x81, 0x7d, 0x69, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff,
	0xc6, 0xbe, 0xd2, 0x80, 0x38, 0x01, 0x00, 0x00,
}

func (m *IDData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IDData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *IDData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Value != nil {
		{
			size, err := m.Value.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintIdData(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintIdData(dAtA []byte, offset int, v uint64) int {
	offset -= sovIdData(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *IDData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Value != nil {
		l = m.Value.Size()
		n += 1 + l + sovIdData(uint64(l))
	}
	return n
}

func sovIdData(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozIdData(x uint64) (n int) {
	return sovIdData(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *IDData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIdData
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IDData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IDData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIdData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthIdData
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthIdData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Value == nil {
				m.Value = &base.AnyID{}
			}
			if err := m.Value.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipIdData(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthIdData
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipIdData(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowIdData
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowIdData
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowIdData
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthIdData
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupIdData
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthIdData
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthIdData        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowIdData          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupIdData = fmt.Errorf("proto: unexpected end of group")
)
