// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: data/base/list_data.proto

package base

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ListData struct {
	AnyListableData []*AnyListableData `protobuf:"bytes,1,rep,name=any_listable_data,json=anyListableData,proto3" json:"any_listable_data,omitempty"`
}

func (m *ListData) Reset()         { *m = ListData{} }
func (m *ListData) String() string { return proto.CompactTextString(m) }
func (*ListData) ProtoMessage()    {}
func (*ListData) Descriptor() ([]byte, []int) {
	return fileDescriptor_91cb79b0f8a6b6b6, []int{0}
}
func (m *ListData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ListData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ListData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListData.Merge(m, src)
}
func (m *ListData) XXX_Size() int {
	return m.Size()
}
func (m *ListData) XXX_DiscardUnknown() {
	xxx_messageInfo_ListData.DiscardUnknown(m)
}

var xxx_messageInfo_ListData proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ListData)(nil), "assetmantle.schema.data.base.ListData")
}

func init() { proto.RegisterFile("data/base/list_data.proto", fileDescriptor_91cb79b0f8a6b6b6) }

var fileDescriptor_91cb79b0f8a6b6b6 = []byte{
	// 299 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4c, 0x49, 0x2c, 0x49,
	0xd4, 0x4f, 0x4a, 0x2c, 0x4e, 0xd5, 0xcf, 0xc9, 0x2c, 0x2e, 0x89, 0x07, 0x71, 0xf5, 0x0a, 0x8a,
	0xf2, 0x4b, 0xf2, 0x85, 0x64, 0x12, 0x8b, 0x8b, 0x53, 0x4b, 0x72, 0x13, 0xf3, 0x4a, 0x72, 0x52,
	0xf5, 0x8a, 0x93, 0x33, 0x52, 0x73, 0x13, 0xf5, 0xc0, 0xd2, 0x20, 0xd5, 0x52, 0x8a, 0x08, 0x8d,
	0x89, 0x79, 0x95, 0xf1, 0x20, 0xcd, 0x89, 0x49, 0x39, 0xa9, 0x48, 0x06, 0x48, 0x89, 0xa4, 0xe7,
	0xa7, 0xe7, 0x83, 0x99, 0xfa, 0x20, 0x16, 0x44, 0x54, 0x29, 0x9b, 0x8b, 0xc3, 0x27, 0xb3, 0xb8,
	0xc4, 0x25, 0xb1, 0x24, 0x51, 0x28, 0x92, 0x4b, 0x10, 0x43, 0xb3, 0x04, 0xa3, 0x02, 0xb3, 0x06,
	0xb7, 0x91, 0xae, 0x1e, 0x3e, 0xeb, 0xf5, 0x1c, 0xf3, 0x2a, 0x7d, 0xa0, 0xba, 0x40, 0x26, 0x05,
	0xf1, 0x27, 0xa2, 0x0a, 0x58, 0xb1, 0x74, 0x2c, 0x90, 0x67, 0x70, 0xea, 0x64, 0x3a, 0xf1, 0x48,
	0x8e, 0xf1, 0xc2, 0x23, 0x39, 0xc6, 0x07, 0x8f, 0xe4, 0x18, 0x27, 0x3c, 0x96, 0x63, 0xb8, 0xf0,
	0x58, 0x8e, 0xe1, 0xc6, 0x63, 0x39, 0x06, 0x2e, 0x85, 0xe4, 0xfc, 0x5c, 0xbc, 0x76, 0x38, 0xf1,
	0xc2, 0xdc, 0x19, 0x00, 0x72, 0x78, 0x00, 0x63, 0x94, 0x56, 0x7a, 0x66, 0x49, 0x46, 0x69, 0x92,
	0x5e, 0x72, 0x7e, 0xae, 0xbe, 0x23, 0x48, 0xa7, 0x2f, 0x58, 0xa7, 0x3e, 0x44, 0xa7, 0x7e, 0x7a,
	0xbe, 0x3e, 0x3c, 0x50, 0x16, 0x31, 0xb1, 0x38, 0x06, 0xbb, 0x38, 0xad, 0x62, 0x92, 0x71, 0x44,
	0xb2, 0x22, 0x18, 0x62, 0x05, 0xc8, 0x4c, 0x3d, 0xa7, 0xc4, 0xe2, 0xd4, 0x53, 0x28, 0xd2, 0x31,
	0x10, 0xe9, 0x18, 0x90, 0x74, 0x0c, 0x48, 0xfa, 0x11, 0x93, 0x06, 0x3e, 0xe9, 0x18, 0xf7, 0x00,
	0x27, 0xdf, 0xd4, 0x92, 0x44, 0x90, 0xa5, 0xaf, 0x98, 0xe4, 0x91, 0x94, 0x5a, 0x59, 0x41, 0xd4,
	0x5a, 0x59, 0x81, 0xc3, 0xc2, 0x0a, 0xa4, 0x3a, 0x89, 0x0d, 0x1c, 0xfe, 0xc6, 0x80, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xac, 0x25, 0x91, 0xd1, 0xf3, 0x01, 0x00, 0x00,
}

func (m *ListData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ListData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AnyListableData) > 0 {
		for iNdEx := len(m.AnyListableData) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AnyListableData[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintListData(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintListData(dAtA []byte, offset int, v uint64) int {
	offset -= sovListData(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ListData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.AnyListableData) > 0 {
		for _, e := range m.AnyListableData {
			l = e.Size()
			n += 1 + l + sovListData(uint64(l))
		}
	}
	return n
}

func sovListData(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozListData(x uint64) (n int) {
	return sovListData(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ListData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowListData
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AnyListableData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowListData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthListData
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthListData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AnyListableData = append(m.AnyListableData, &AnyListableData{})
			if err := m.AnyListableData[len(m.AnyListableData)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipListData(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthListData
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipListData(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowListData
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowListData
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowListData
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthListData
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupListData
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthListData
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthListData        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowListData          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupListData = fmt.Errorf("proto: unexpected end of group")
)
