// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: documents/base/document.proto

package base

import (
	fmt "fmt"
	base "github.com/AssetMantle/schema/go/ids/base"
	base1 "github.com/AssetMantle/schema/go/qualified/base"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Document struct {
	ClassificationID *base.ClassificationID `protobuf:"bytes,1,opt,name=classification_i_d,json=classificationID,proto3" json:"classification_i_d,omitempty"`
	Immutables       *base1.Immutables      `protobuf:"bytes,2,opt,name=immutables,proto3" json:"immutables,omitempty"`
	Mutables         *base1.Mutables        `protobuf:"bytes,3,opt,name=mutables,proto3" json:"mutables,omitempty"`
}

func (m *Document) Reset()         { *m = Document{} }
func (m *Document) String() string { return proto.CompactTextString(m) }
func (*Document) ProtoMessage()    {}
func (*Document) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a913b9da3833a5e, []int{0}
}
func (m *Document) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Document) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Document.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Document) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Document.Merge(m, src)
}
func (m *Document) XXX_Size() int {
	return m.Size()
}
func (m *Document) XXX_DiscardUnknown() {
	xxx_messageInfo_Document.DiscardUnknown(m)
}

var xxx_messageInfo_Document proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Document)(nil), "assetmantle.schema.documents.base.Document")
}

func init() { proto.RegisterFile("documents/base/document.proto", fileDescriptor_5a913b9da3833a5e) }

var fileDescriptor_5a913b9da3833a5e = []byte{
	// 379 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcd, 0x4a, 0xeb, 0x40,
	0x18, 0x86, 0x93, 0x9c, 0x72, 0x28, 0x39, 0x1c, 0x90, 0xe0, 0xa2, 0x14, 0x9a, 0xb6, 0xa2, 0x20,
	0x48, 0x67, 0x40, 0x77, 0xd9, 0x35, 0x06, 0x4a, 0x17, 0x81, 0xd2, 0xee, 0x34, 0x50, 0x26, 0xc9,
	0x34, 0x1d, 0x48, 0x3a, 0xea, 0x4c, 0x2e, 0x41, 0x70, 0xe9, 0x25, 0x88, 0x1b, 0xc1, 0x2b, 0x11,
	0x57, 0x5d, 0xba, 0x94, 0x74, 0xe7, 0x55, 0x48, 0x32, 0xe9, 0xd8, 0x14, 0xa5, 0xee, 0xf2, 0xf3,
	0x3c, 0xef, 0xf7, 0x66, 0xf2, 0xe9, 0xad, 0x90, 0x06, 0x69, 0x82, 0x17, 0x9c, 0x41, 0x1f, 0x31,
	0x0c, 0xd7, 0xb7, 0xe0, 0xea, 0x86, 0x72, 0x6a, 0x74, 0x11, 0x63, 0x98, 0x27, 0x68, 0xc1, 0x63,
	0x0c, 0x58, 0x30, 0xc7, 0x09, 0x02, 0xd2, 0x00, 0xb9, 0xd1, 0xdc, 0x8f, 0x68, 0x44, 0x0b, 0x1a,
	0xe6, 0x57, 0x42, 0x6c, 0x76, 0x48, 0x58, 0x26, 0x06, 0x31, 0x62, 0x8c, 0xcc, 0x48, 0x80, 0x38,
	0xa1, 0x8b, 0x29, 0x09, 0x4b, 0xa2, 0x7d, 0x9d, 0xa2, 0x98, 0xcc, 0x08, 0x0e, 0x05, 0x47, 0x92,
	0x24, 0xe5, 0xc8, 0x8f, 0x31, 0x2b, 0x81, 0xd6, 0x16, 0x50, 0x7d, 0x7d, 0x70, 0xab, 0xe9, 0x75,
	0xa7, 0xac, 0x62, 0x5c, 0xea, 0xc6, 0xf6, 0x9c, 0x69, 0xd8, 0x50, 0x3b, 0xea, 0xf1, 0xbf, 0xd3,
	0x1e, 0xf8, 0xe6, 0x23, 0x48, 0x28, 0xea, 0x83, 0xf3, 0x8a, 0x36, 0x74, 0xc6, 0x7b, 0xc1, 0xd6,
	0x13, 0xc3, 0xd5, 0xf5, 0xaf, 0x72, 0x0d, 0xed, 0xe7, 0x50, 0x59, 0x58, 0x44, 0x0f, 0xa5, 0x34,
	0xde, 0x08, 0x30, 0x06, 0x7a, 0x5d, 0x86, 0xfd, 0x29, 0xc2, 0x4e, 0x7e, 0x11, 0xe6, 0xae, 0xa3,
	0xa4, 0x6c, 0xd5, 0xee, 0x1e, 0xda, 0x8a, 0xfd, 0xa4, 0xbd, 0x64, 0xa6, 0xba, 0xcc, 0x4c, 0xf5,
	0x3d, 0x33, 0xd5, 0xfb, 0x95, 0xa9, 0x2c, 0x57, 0xa6, 0xf2, 0xb6, 0x32, 0x15, 0xfd, 0x28, 0xa0,
	0x09, 0xd8, 0xf9, 0x07, 0xed, 0xff, 0xeb, 0x63, 0x1c, 0xe5, 0x07, 0x3b, 0x52, 0x2f, 0x60, 0x44,
	0xf8, 0x3c, 0xf5, 0x41, 0x40, 0x13, 0xd8, 0xcf, 0x75, 0xb7, 0xd0, 0xa1, 0xd0, 0x61, 0x44, 0x61,
	0x75, 0x6b, 0x1e, 0xb5, 0x5a, 0x7f, 0xe2, 0xd8, 0xcf, 0x5a, 0xb7, 0xbf, 0x31, 0x6c, 0x22, 0x86,
	0x39, 0x72, 0x98, 0x8d, 0x18, 0x7e, 0xad, 0x30, 0x9e, 0x60, 0x3c, 0xc9, 0x78, 0x39, 0x93, 0x69,
	0xbd, 0x9d, 0x8c, 0x37, 0x18, 0xd9, 0x2e, 0xe6, 0x28, 0x44, 0x1c, 0x7d, 0x68, 0x87, 0x1b, 0xbc,
	0x65, 0x09, 0xc1, 0xb2, 0xa4, 0x61, 0x59, 0xb9, 0xe2, 0xff, 0x2d, 0x16, 0xe7, 0xec, 0x33, 0x00,
	0x00, 0xff, 0xff, 0x72, 0x9b, 0xa9, 0xdb, 0xf4, 0x02, 0x00, 0x00,
}

func (m *Document) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Document) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Document) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Mutables != nil {
		{
			size, err := m.Mutables.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintDocument(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.Immutables != nil {
		{
			size, err := m.Immutables.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintDocument(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.ClassificationID != nil {
		{
			size, err := m.ClassificationID.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintDocument(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintDocument(dAtA []byte, offset int, v uint64) int {
	offset -= sovDocument(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Document) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ClassificationID != nil {
		l = m.ClassificationID.Size()
		n += 1 + l + sovDocument(uint64(l))
	}
	if m.Immutables != nil {
		l = m.Immutables.Size()
		n += 1 + l + sovDocument(uint64(l))
	}
	if m.Mutables != nil {
		l = m.Mutables.Size()
		n += 1 + l + sovDocument(uint64(l))
	}
	return n
}

func sovDocument(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDocument(x uint64) (n int) {
	return sovDocument(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Document) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDocument
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Document: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Document: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClassificationID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDocument
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDocument
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDocument
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ClassificationID == nil {
				m.ClassificationID = &base.ClassificationID{}
			}
			if err := m.ClassificationID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Immutables", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDocument
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDocument
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDocument
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Immutables == nil {
				m.Immutables = &base1.Immutables{}
			}
			if err := m.Immutables.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mutables", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDocument
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDocument
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDocument
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Mutables == nil {
				m.Mutables = &base1.Mutables{}
			}
			if err := m.Mutables.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDocument(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDocument
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDocument(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDocument
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDocument
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDocument
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDocument
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDocument
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDocument
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDocument        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDocument          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDocument = fmt.Errorf("proto: unexpected end of group")
)
