// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: AssetMantle/schema/properties/base/meta_property.proto

package base

import (
	fmt "fmt"
	base1 "github.com/AssetMantle/schema/data/base"
	base "github.com/AssetMantle/schema/ids/base"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MetaProperty struct {
	ID   *base.PropertyID `protobuf:"bytes,1,opt,name=i_d,json=iD,proto3" json:"i_d,omitempty"`
	Data *base1.AnyData   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *MetaProperty) Reset()         { *m = MetaProperty{} }
func (m *MetaProperty) String() string { return proto.CompactTextString(m) }
func (*MetaProperty) ProtoMessage()    {}
func (*MetaProperty) Descriptor() ([]byte, []int) {
	return fileDescriptor_91e80dcec34e1962, []int{0}
}
func (m *MetaProperty) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MetaProperty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MetaProperty.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MetaProperty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaProperty.Merge(m, src)
}
func (m *MetaProperty) XXX_Size() int {
	return m.Size()
}
func (m *MetaProperty) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaProperty.DiscardUnknown(m)
}

var xxx_messageInfo_MetaProperty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MetaProperty)(nil), "AssetMantle.schema.properties.base.MetaProperty")
}

func init() {
	proto.RegisterFile("AssetMantle/schema/properties/base/meta_property.proto", fileDescriptor_91e80dcec34e1962)
}

var fileDescriptor_91e80dcec34e1962 = []byte{
	// 345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x73, 0x2c, 0x2e, 0x4e,
	0x2d, 0xf1, 0x4d, 0xcc, 0x2b, 0xc9, 0x49, 0xd5, 0x2f, 0x4e, 0xce, 0x48, 0xcd, 0x4d, 0xd4, 0x2f,
	0x28, 0xca, 0x2f, 0x48, 0x2d, 0x2a, 0xc9, 0x4c, 0x2d, 0xd6, 0x4f, 0x4a, 0x2c, 0x4e, 0xd5, 0xcf,
	0x4d, 0x2d, 0x49, 0x8c, 0x87, 0x0a, 0x56, 0xea, 0x15, 0x14, 0xe5, 0x97, 0xe4, 0x0b, 0x29, 0x21,
	0xe9, 0xd3, 0x83, 0xe8, 0xd3, 0x43, 0xe8, 0xd3, 0x03, 0xe9, 0x93, 0xd2, 0xc6, 0x62, 0x76, 0x4a,
	0x62, 0x49, 0x22, 0xc4, 0xd4, 0xc4, 0xbc, 0xca, 0x78, 0x10, 0x0f, 0x62, 0xa0, 0x94, 0x48, 0x7a,
	0x7e, 0x7a, 0x3e, 0x98, 0xa9, 0x0f, 0x62, 0x41, 0x45, 0x75, 0xb1, 0x18, 0x91, 0x99, 0x02, 0x75,
	0x17, 0xcc, 0x49, 0xf1, 0x99, 0x29, 0x10, 0xe5, 0x4a, 0x9d, 0x8c, 0x5c, 0x3c, 0xbe, 0xa9, 0x25,
	0x89, 0x01, 0x50, 0x19, 0x21, 0x0b, 0x2e, 0xe6, 0xcc, 0xf8, 0x14, 0x09, 0x46, 0x05, 0x46, 0x0d,
	0x6e, 0x23, 0x75, 0x3d, 0x2c, 0x8e, 0xce, 0x4c, 0x81, 0xb8, 0x56, 0x0f, 0xa6, 0xc7, 0xd3, 0x25,
	0x88, 0x29, 0xd3, 0x45, 0xc8, 0x92, 0x8b, 0x05, 0xe4, 0x3a, 0x09, 0x26, 0xb0, 0x56, 0x55, 0x6c,
	0x5a, 0xc1, 0xae, 0x07, 0xeb, 0x75, 0xcc, 0xab, 0x74, 0x49, 0x2c, 0x49, 0x0c, 0x02, 0x6b, 0xb1,
	0x62, 0xe9, 0x58, 0x20, 0xcf, 0xe0, 0xb4, 0x8e, 0xe9, 0xc4, 0x23, 0x39, 0xc6, 0x0b, 0x8f, 0xe4,
	0x18, 0x1f, 0x3c, 0x92, 0x63, 0x9c, 0xf0, 0x58, 0x8e, 0xe1, 0xc2, 0x63, 0x39, 0x86, 0x1b, 0x8f,
	0xe5, 0x18, 0xb8, 0xd4, 0x92, 0xf3, 0x73, 0xf5, 0x08, 0x07, 0xa0, 0x93, 0x20, 0xb2, 0x5f, 0x02,
	0x40, 0x3e, 0x0c, 0x60, 0x8c, 0xd2, 0x4d, 0xcf, 0x2c, 0xc9, 0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf,
	0xd5, 0x27, 0x1c, 0x79, 0x8b, 0x98, 0x58, 0x1c, 0x83, 0x03, 0x9c, 0x56, 0x31, 0xa1, 0x44, 0x58,
	0x30, 0xc4, 0xbe, 0x00, 0x84, 0x7d, 0x4e, 0x89, 0xc5, 0xa9, 0xa7, 0x50, 0x14, 0xc5, 0x40, 0x14,
	0xc5, 0x20, 0x14, 0xc5, 0x80, 0x14, 0x3d, 0x62, 0xd2, 0x23, 0xac, 0x28, 0xc6, 0x3d, 0xc0, 0x09,
	0xe4, 0x76, 0x50, 0x70, 0xbc, 0x62, 0x52, 0x45, 0xd2, 0x60, 0x65, 0x05, 0xd1, 0x61, 0x65, 0x85,
	0xd0, 0x62, 0x65, 0x05, 0xd2, 0x93, 0xc4, 0x06, 0x8e, 0x43, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x5a, 0xc4, 0x08, 0x1d, 0x93, 0x02, 0x00, 0x00,
}

func (m *MetaProperty) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MetaProperty) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MetaProperty) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Data != nil {
		{
			size, err := m.Data.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMetaProperty(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.ID != nil {
		{
			size, err := m.ID.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMetaProperty(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintMetaProperty(dAtA []byte, offset int, v uint64) int {
	offset -= sovMetaProperty(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MetaProperty) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ID != nil {
		l = m.ID.Size()
		n += 1 + l + sovMetaProperty(uint64(l))
	}
	if m.Data != nil {
		l = m.Data.Size()
		n += 1 + l + sovMetaProperty(uint64(l))
	}
	return n
}

func sovMetaProperty(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMetaProperty(x uint64) (n int) {
	return sovMetaProperty(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MetaProperty) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMetaProperty
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MetaProperty: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MetaProperty: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetaProperty
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMetaProperty
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMetaProperty
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ID == nil {
				m.ID = &base.PropertyID{}
			}
			if err := m.ID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetaProperty
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMetaProperty
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMetaProperty
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Data == nil {
				m.Data = &base1.AnyData{}
			}
			if err := m.Data.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMetaProperty(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMetaProperty
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMetaProperty(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMetaProperty
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMetaProperty
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMetaProperty
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMetaProperty
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMetaProperty
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMetaProperty
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMetaProperty        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMetaProperty          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMetaProperty = fmt.Errorf("proto: unexpected end of group")
)
