// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ids/base/split_id.proto

package base

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type SplitID struct {
	OwnerID   *IdentityID   `protobuf:"bytes,1,opt,name=owner_i_d,json=ownerID,proto3" json:"owner_i_d,omitempty"`
	OwnableID *AnyOwnableID `protobuf:"bytes,2,opt,name=ownable_i_d,json=ownableID,proto3" json:"ownable_i_d,omitempty"`
}

func (m *SplitID) Reset()         { *m = SplitID{} }
func (m *SplitID) String() string { return proto.CompactTextString(m) }
func (*SplitID) ProtoMessage()    {}
func (*SplitID) Descriptor() ([]byte, []int) {
	return fileDescriptor_1253af3276df6cff, []int{0}
}
func (m *SplitID) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SplitID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SplitID.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SplitID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SplitID.Merge(m, src)
}
func (m *SplitID) XXX_Size() int {
	return m.Size()
}
func (m *SplitID) XXX_DiscardUnknown() {
	xxx_messageInfo_SplitID.DiscardUnknown(m)
}

var xxx_messageInfo_SplitID proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SplitID)(nil), "ids.SplitID")
}

func init() { proto.RegisterFile("ids/base/split_id.proto", fileDescriptor_1253af3276df6cff) }

var fileDescriptor_1253af3276df6cff = []byte{
	// 301 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcf, 0x4c, 0x29, 0xd6,
	0x4f, 0x4a, 0x2c, 0x4e, 0xd5, 0x2f, 0x2e, 0xc8, 0xc9, 0x2c, 0x89, 0xcf, 0x4c, 0xd1, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0x4c, 0x29, 0x96, 0x92, 0x82, 0xcb, 0x66, 0xa6, 0xa4, 0xe6,
	0x95, 0x64, 0x96, 0x54, 0xc2, 0x15, 0x48, 0xc9, 0xc2, 0xe5, 0x12, 0xf3, 0x2a, 0xe3, 0xf3, 0xcb,
	0xf3, 0x12, 0x93, 0x72, 0x52, 0x11, 0xd2, 0x22, 0xe9, 0xf9, 0xe9, 0xf9, 0x60, 0xa6, 0x3e, 0x88,
	0x05, 0x11, 0x55, 0xca, 0xe7, 0x62, 0x0f, 0x06, 0xd9, 0xe3, 0xe9, 0x22, 0xa4, 0xcd, 0xc5, 0x99,
	0x5f, 0x9e, 0x97, 0x5a, 0x14, 0x9f, 0x19, 0x9f, 0x22, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x6d, 0xc4,
	0xaf, 0x97, 0x99, 0x52, 0xac, 0xe7, 0x09, 0xb5, 0xca, 0xd3, 0x25, 0x88, 0x1d, 0xac, 0xc2, 0xd3,
	0x45, 0xc8, 0x90, 0x8b, 0x1b, 0x6e, 0x43, 0x7c, 0x8a, 0x04, 0x13, 0x58, 0xb9, 0x20, 0x58, 0xb9,
	0x63, 0x5e, 0xa5, 0x3f, 0x44, 0xca, 0xd3, 0x25, 0x88, 0x33, 0x1f, 0xc6, 0xb4, 0x62, 0xe9, 0x58,
	0x20, 0xcf, 0xe0, 0xd4, 0xc6, 0x78, 0xe2, 0x91, 0x1c, 0xe3, 0x85, 0x47, 0x72, 0x8c, 0x0f, 0x1e,
	0xc9, 0x31, 0x4e, 0x78, 0x2c, 0xc7, 0x70, 0xe1, 0xb1, 0x1c, 0xc3, 0x8d, 0xc7, 0x72, 0x0c, 0x5c,
	0xec, 0xc9, 0xf9, 0xb9, 0x20, 0x13, 0x9c, 0x78, 0x20, 0x4e, 0x4a, 0x09, 0x00, 0x39, 0x31, 0x80,
	0x31, 0x4a, 0x33, 0x3d, 0xb3, 0x24, 0xa3, 0x34, 0x49, 0x2f, 0x39, 0x3f, 0x57, 0xdf, 0xb1, 0xb8,
	0x38, 0xb5, 0xc4, 0x37, 0x31, 0xaf, 0x24, 0x27, 0x55, 0xbf, 0x38, 0x39, 0x23, 0x35, 0x37, 0x51,
	0x3f, 0x3d, 0x5f, 0x1f, 0xe6, 0xf5, 0x45, 0x4c, 0xcc, 0x9e, 0x11, 0x11, 0xab, 0x98, 0x98, 0x3d,
	0x53, 0x8a, 0x4f, 0x81, 0xc9, 0x47, 0x4c, 0xfc, 0x9e, 0x29, 0xc5, 0x31, 0xee, 0x01, 0x4e, 0xbe,
	0xa9, 0x25, 0x89, 0x29, 0x89, 0x25, 0x89, 0xaf, 0xc0, 0xe2, 0x49, 0x6c, 0xe0, 0x00, 0x30, 0x06,
	0x04, 0x00, 0x00, 0xff, 0xff, 0xae, 0x6e, 0x6d, 0x57, 0x71, 0x01, 0x00, 0x00,
}

func (m *SplitID) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SplitID) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SplitID) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.OwnableID != nil {
		{
			size, err := m.OwnableID.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSplitId(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.OwnerID != nil {
		{
			size, err := m.OwnerID.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSplitId(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintSplitId(dAtA []byte, offset int, v uint64) int {
	offset -= sovSplitId(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SplitID) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.OwnerID != nil {
		l = m.OwnerID.Size()
		n += 1 + l + sovSplitId(uint64(l))
	}
	if m.OwnableID != nil {
		l = m.OwnableID.Size()
		n += 1 + l + sovSplitId(uint64(l))
	}
	return n
}

func sovSplitId(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSplitId(x uint64) (n int) {
	return sovSplitId(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SplitID) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSplitId
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SplitID: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SplitID: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OwnerID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSplitId
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSplitId
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSplitId
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.OwnerID == nil {
				m.OwnerID = &IdentityID{}
			}
			if err := m.OwnerID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OwnableID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSplitId
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSplitId
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSplitId
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.OwnableID == nil {
				m.OwnableID = &AnyOwnableID{}
			}
			if err := m.OwnableID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSplitId(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSplitId
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSplitId(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSplitId
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSplitId
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSplitId
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSplitId
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSplitId
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSplitId
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSplitId        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSplitId          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSplitId = fmt.Errorf("proto: unexpected end of group")
)
