// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: x/ids/base/assetID.proto

package base

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type AssetID struct {
	HashID *HashID `protobuf:"bytes,1,opt,name=hash_i_d,json=hashID,proto3" json:"hash_i_d,omitempty"`
}

func (m *AssetID) Reset()         { *m = AssetID{} }
func (m *AssetID) String() string { return proto.CompactTextString(m) }
func (*AssetID) ProtoMessage()    {}
func (*AssetID) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d349869e8c0c0e9, []int{0}
}
func (m *AssetID) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AssetID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AssetID.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AssetID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssetID.Merge(m, src)
}
func (m *AssetID) XXX_Size() int {
	return m.Size()
}
func (m *AssetID) XXX_DiscardUnknown() {
	xxx_messageInfo_AssetID.DiscardUnknown(m)
}

var xxx_messageInfo_AssetID proto.InternalMessageInfo

func init() {
	proto.RegisterType((*AssetID)(nil), "ids.AssetID")
}

func init() { proto.RegisterFile("x/ids/base/assetID.proto", fileDescriptor_1d349869e8c0c0e9) }

var fileDescriptor_1d349869e8c0c0e9 = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xa8, 0xd0, 0xcf, 0x4c,
	0x29, 0xd6, 0x4f, 0x4a, 0x2c, 0x4e, 0xd5, 0x4f, 0x2c, 0x2e, 0x4e, 0x2d, 0xf1, 0x74, 0xd1, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0x4c, 0x29, 0x96, 0x12, 0x47, 0x92, 0xce, 0x48, 0x2c,
	0xce, 0x80, 0xc9, 0x4a, 0x89, 0xa4, 0xe7, 0xa7, 0xe7, 0x83, 0x99, 0xfa, 0x20, 0x16, 0x44, 0x54,
	0xc9, 0x8c, 0x8b, 0xdd, 0x11, 0x62, 0x88, 0x90, 0x2a, 0x17, 0x07, 0x48, 0x43, 0x7c, 0x66, 0x7c,
	0x8a, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0xb7, 0x11, 0xb7, 0x5e, 0x66, 0x4a, 0xb1, 0x9e, 0x07, 0xd8,
	0x94, 0x20, 0x36, 0x88, 0x69, 0x56, 0x2c, 0x1d, 0x0b, 0xe4, 0x19, 0x9c, 0x5a, 0x19, 0x4f, 0x3c,
	0x92, 0x63, 0xbc, 0xf0, 0x48, 0x8e, 0xf1, 0xc1, 0x23, 0x39, 0xc6, 0x09, 0x8f, 0xe5, 0x18, 0x2e,
	0x3c, 0x96, 0x63, 0xb8, 0xf1, 0x58, 0x8e, 0x81, 0x8b, 0x3d, 0x39, 0x3f, 0x17, 0xa4, 0xd1, 0x89,
	0x07, 0x6a, 0x72, 0x00, 0xc8, 0xa6, 0x00, 0xc6, 0x28, 0x8d, 0xf4, 0xcc, 0x92, 0x8c, 0xd2, 0x24,
	0xbd, 0xe4, 0xfc, 0x5c, 0x7d, 0xb0, 0x94, 0x6f, 0x62, 0x5e, 0x49, 0x4e, 0xaa, 0x7e, 0x71, 0x72,
	0x46, 0x6a, 0x6e, 0xa2, 0x3e, 0xc2, 0xe1, 0x8b, 0x98, 0x98, 0x3d, 0x23, 0x22, 0x56, 0x31, 0x31,
	0x7b, 0xa6, 0x14, 0x9f, 0x02, 0x93, 0x8f, 0x98, 0xf8, 0x3d, 0x53, 0x8a, 0x63, 0xdc, 0x03, 0x9c,
	0x7c, 0x53, 0x4b, 0x12, 0x53, 0x12, 0x4b, 0x12, 0x5f, 0x81, 0xc5, 0x93, 0xd8, 0xc0, 0xde, 0x30,
	0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xd8, 0x36, 0xdf, 0xae, 0x16, 0x01, 0x00, 0x00,
}

func (m *AssetID) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AssetID) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AssetID) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.HashID != nil {
		{
			size, err := m.HashID.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAssetID(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintAssetID(dAtA []byte, offset int, v uint64) int {
	offset -= sovAssetID(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AssetID) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.HashID != nil {
		l = m.HashID.Size()
		n += 1 + l + sovAssetID(uint64(l))
	}
	return n
}

func sovAssetID(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAssetID(x uint64) (n int) {
	return sovAssetID(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *AssetID) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAssetID
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AssetID: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AssetID: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HashID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAssetID
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAssetID
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAssetID
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.HashID == nil {
				m.HashID = &HashID{}
			}
			if err := m.HashID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAssetID(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAssetID
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAssetID(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAssetID
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAssetID
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAssetID
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAssetID
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAssetID
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAssetID
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAssetID        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAssetID          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAssetID = fmt.Errorf("proto: unexpected end of group")
)
